-- Add micronutrient columns to food_library table
-- Run this migration in your Supabase SQL editor

ALTER TABLE food_library
ADD COLUMN IF NOT EXISTS vitamin_a_mcg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b1_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b2_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b3_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b5_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b6_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b7_mcg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b9_mcg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_b12_mcg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_c_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_d_mcg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_e_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vitamin_k_mcg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS calcium_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS iron_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS magnesium_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS phosphorus_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS potassium_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS sodium_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS zinc_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS copper_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS manganese_mg DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS selenium_mcg DECIMAL DEFAULT 0;
